### PR TITLE
Support both bcrypt and certain legacy encryptor

### PR DESCRIPTION
**Pull request by zimuliu**
@omikronn @cdmicacc please CR

This is needed to support two encryptors at the same time.

### CODE REVIEW

**Comment by cdmicacc** [comment]
Is the intention that Community users would slowly switch to bcrypt as they change their password (or as new users sign up)?

**Comment by cdmicacc** [comment]
Also, should this repo be renamed `px-devise-encryptable` since that's the gem name?

**Comment by zimuliu** [comment]
yep, will do it later

**Comment by zimuliu** [comment]
@cdmicacc the intention is to make sure password from Prime will also work in 500px (and vice verse).  Migrating to bcrypt is kind of side-effect of this change, for better security and performance.

**Comment by cdmicacc** [comment]
Cool. Ok, :+1:

**Pull request merged**
